// Caption Copywriting -- Multi-Platform Reference
// Ported from ai-image-carousel-prompt-gen/references/caption-copywriting.md
// RAG knowledge injected into LLM prompts for carousel caption generation

export const CAPTION_COPYWRITING_KNOWLEDGE = `
CAPTION COPYWRITING -- MULTI-PLATFORM REFERENCE

Configurable values (handle, portfolio URL, hashtag limits, caption language) are in global config.
This file contains caption formulas, tone guidance, and platform-specific writing tips.

DEFAULT LANGUAGE
Caption language: per global config (caption_language). Other language only when user explicitly requests.
Captions for all 4 platforms (IG + TikTok + LinkedIn + Threads) are generated by DEFAULT with every carousel output.
User can say "IG aja" or "skip LinkedIn" to filter.

---

1. PLATFORM CHARACTER LIMITS

| Platform        | Max Characters | Truncation Point          | What Shows Before "...more"              |
|-----------------|---------------|--------------------------|------------------------------------------|
| Instagram       | 2,200         | 125 chars                | First ~125 chars in feed                 |
| TikTok Title    | 19            | N/A (always visible)     | Separate field above caption -- primary SEO keyword |
| TikTok Caption  | 4,000         | ~100-150 chars           | First ~100-150 chars in FYP              |
| LinkedIn        | 3,000         | 210 (desktop) / 110 (mobile) | First line before "...see more"      |
| Threads         | 500           | ~100 chars               | First ~100 chars in feed                 |

Rule: Your hook MUST land before the truncation point. Everything after is bonus.

---

2. HASHTAG STRATEGY (5-HASHTAG ERA)

Since late 2025, both Instagram and TikTok penalize hashtag spam. Less is more.

| Platform  | Max Hashtags | Formula                          | Placement              |
|-----------|-------------|----------------------------------|------------------------|
| Instagram | 5 (Dec 2025 update) | 2 broad + 2 niche + 1 branded | In caption body (not comments) |
| TikTok    | 5 (Aug 2025 update) | 2 broad + 2 niche + 1 branded | End of caption         |
| LinkedIn  | 3-5         | Industry-specific, not generic   | End of post            |

HASHTAG FORMULA: 2-2-1
2 BROAD:   High-volume, category-level (#AI, #TechTips)
2 NICHE:   Specific to topic (#AIImageGeneration, #CarouselDesign)
1 BRANDED: Your handle or series name (#YourBrand, #YourSeries)

WHAT NOT TO DO:
- No banned/flagged hashtags (check before posting)
- No generic filler (#love, #instagood, #fyp)
- No more than 5 -- platforms actively suppress >5 hashtag posts
- No hashtag-first captions -- hook first, hashtags at end
- No same hashtag set on every post -- rotate to avoid spam filters

THE HASHTAG ROLE SHIFT (2025-2026)

Hashtags are now topic labels for categorization, NOT reach drivers. All 3 platforms moved to AI-powered semantic discovery.

| Platform  | Real Reach Driver                                           | Hashtag Role                        |
|-----------|-------------------------------------------------------------|-------------------------------------|
| Instagram | Caption keywords (+30% more reach than hashtag-heavy posts) | Topic labeling for search index     |
| TikTok    | Caption keywords (+20-40% visibility boost)                 | Content categorization + search     |
| LinkedIn  | Semantic AI reads full post text directly                    | SEO keyword for search only         |

Key shifts:
- Instagram removed hashtag following (Dec 2024) and reduced algorithmic weight
- LinkedIn removed hashtag following, "Talks About" section, and hashtag suggestions (late 2024)
- TikTok indexes on-screen text via OCR -- hashtags are secondary to caption keywords
- Instagram captions now appear in Google search results (July 2025)

AVOIDING SHADOWBAN TRIGGERS:
- Check each hashtag before posting -- if search shows zero results, it may be restricted
- Never use identical hashtag set on consecutive posts
- Avoid bot-like behavior (mass follow/unfollow, copy-paste comments)
- No cross-platform watermarks (IG deprioritizes TikTok watermarks and vice versa)
- No irrelevant hashtags -- causes algorithmic confusion + potential suppression
- If shadowbanned: stop posting 48-72h, delete flagged content, clear cache, remove banned tags

---

3. CAPTION FORMULA PER PLATFORM

INSTAGRAM CAPTION FORMULA

[Pattern interrupt -- question, bold claim, or shocking stat (<=125 chars before truncation)]

[Context, backstory, or deeper insight not in the slides]
[Personal experience or data point]

[Specific ask: save, share, follow, comment, link in bio]

#Broad1 #Broad2 #Niche1 #Niche2 #Branded

Instagram Tone: Visual storytelling, personal, community-driven. Use line breaks for readability. Emojis OK but not excessive.

Output format: One continuous caption -- NO section labels (Hook/Body/CTA/Hashtags). Hashtags at the end, no label.

CHARACTER BUDGET:
| Section   | Max Chars | Notes                    |
|-----------|----------|--------------------------|
| Hook      | 125      | Must work as standalone  |
| Body      | 1,800    | Expand on carousel, don't repeat |
| CTA       | 100      | One clear action         |
| Hashtags  | 175      | 5 hashtags max           |
| Total     | <=2,200  |                          |

TIKTOK CAPTION FORMULA

TikTok has 2 separate fields: Title + Caption.

Title (19 chars max -- SEPARATE field above caption):
[Primary SEO keyword -- max 19 characters, no hashtags, no emoji]
- Title is ALWAYS visible above the caption (never truncated)
- Must contain the primary search keyword for the topic
- TikTok indexes the title as the highest-weight SEO signal
- Keep it short, punchy, keyword-dense (e.g., "AI Tools 2026", "Figma Tips", "Passive Income")

Caption:
[Casual, trend-aware, Gen Z hook (<=100 chars before truncation) -- "POV:", "Wait for it...", provocative question]

[TikTok search indexes captions -- include searchable keywords]
[Short paragraphs, punchy sentences]

[Ask question -> drive comments. "Save for later" -> drive saves]

#Broad1 #Broad2 #Niche1 #Niche2 #Branded

TikTok Tone: Casual, trend-native, conversational. Use text-speak sparingly. Write like you talk. No corporate polish.

Output format: Title on first line (labeled Title:), then one continuous caption -- NO section labels. Hashtags at the end, no label.

CHARACTER BUDGET:
| Section        | Max Chars | Notes                                            |
|----------------|----------|--------------------------------------------------|
| Title          | 19       | SEPARATE field -- primary SEO keyword, always visible |
| Hook           | 100      | Must survive truncation                          |
| Body           | 3,600    | SEO keywords for search                          |
| CTA            | 150      | Question + save/share ask                        |
| Hashtags       | 150      | 5 hashtags max                                   |
| Caption Total  | <=4,000  | Title is separate, not counted                   |

LINKEDIN CAPTION FORMULA

[Professional insight, contrarian take, or industry data (<=110 chars before truncation)]
[LINE BREAK -- forces "...see more" click]

[Personal story or framework]
[Data-backed insight]
[Actionable takeaway]

[Open question inviting expertise sharing]
[Optional: "Repost if you agree" for share signal]

[Link to full article, tool, or resource]

Per global config LinkedIn Cross-Promotion Block

#IndustryTag1 #IndustryTag2 #TopicTag

LinkedIn Cross-Promotion (MANDATORY): Every LinkedIn caption must end with the cross-promotion block from global config (LinkedIn Cross-Promotion Block section) before hashtags.

LinkedIn Tone: Professional but human. Thought leadership. Share frameworks, not tips. Use "I" statements for authority. No emojis in first line.

Output format: One continuous caption -- NO section labels. Link inline if applicable. Hashtags at the end, no label.

CHARACTER BUDGET:
| Section   | Max Chars | Notes                                   |
|-----------|----------|-----------------------------------------|
| Hook      | 110      | Must work on mobile (110 char truncation) |
| Body      | 2,500    | Thought leadership, frameworks          |
| CTA       | 200      | Open question + repost ask              |
| Link      | 100      | One link only                           |
| Hashtags  | 90       | 3-5 industry hashtags                   |
| Total     | <=3,000  |                                         |

THREADS CAPTION FORMULA

[Conversational hook -- opinion or hot take (<=100 chars before truncation)]

[Short opinion-driven body -- personal, community-first]
[Threads rewards conversation starters, keep it punchy]

[Question or opinion prompt to drive replies]

Threads Tone: Conversational, opinion-driven, community-first. No hashtags (Threads does not use hashtags for discovery). Write like a group chat message to your smartest friends.

Output format: One continuous caption -- NO section labels. NO hashtags on Threads.

CHARACTER BUDGET:
| Section | Max Chars | Notes                          |
|---------|----------|--------------------------------|
| Hook    | 100      | Must work as standalone in feed |
| Body    | 300      | Short, punchy, opinion-driven  |
| CTA     | 100      | Question or opinion prompt     |
| Total   | <=500    |                                |

---

4. EMOTIONAL TRIGGERS PER PLATFORM

| Trigger                  | Instagram                          | TikTok                             | LinkedIn                                    |
|--------------------------|------------------------------------|------------------------------------|---------------------------------------------|
| Curiosity gap            | "I tested 50 tools. Only 3 worked." | "No one tells you about..."       | "After 5 years, here's what I learned:"     |
| Vulnerability            | Personal story + lesson learned    | Self-deprecating humor, oddly specific relatability | Professional failure story + framework |
| FOMO                     | "Only available this week"         | "Only 1% of people know..."       | "The companies doing this are pulling ahead" |
| Hot take / Contrarian    | "Stop posting Reels. Here's why."  | "Unpopular opinion: [bold claim]"  | "Unpopular opinion: [industry take]"        |
| Social proof             | Testimonials, before/after         | "If you know, you know"           | Data-backed insights, case studies          |
| Aspiration               | Transformation stories             | "I did X in just Y days"          | Career journey, milestone sharing           |

TIKTOK-SPECIFIC LANGUAGE PATTERNS (Gen Z / Millennial):
- Lowercase aesthetic -- intentional lack of capitalization signals casualness
- Oddly specific relatability -- the more niche, the better it resonates ("When your brother tried to cut the line at Thanksgiving but you've lived off cottage cheese and salads for an entire year")
- Hyperbolic minimalism -- "This is everything" / "I'm deceased"
- Self-call-out -- "Not me [doing something relatable]..."
- Trailing emphasis -- "The way [thing happened]..."
- Ironic detachment -- self-aware humor about own habits
- Yellow font = vulnerable -- Gen Z color-coded system for deeply personal content

LINKEDIN ENGAGEMENT BAIT -- AVOID THESE:
LinkedIn's 2026 algorithm uses NLP to detect and actively suppress engagement bait (-60% reach penalty):
- "Comment YES if you agree" -- penalized
- "Type 1 if you agree, 2 if you disagree" -- penalized
- "Like for A, Heart for B" (reaction polling) -- penalized
- Engagement pods (reciprocal patterns) -- AI detects, applies shadowban

What works instead: Naturally thought-provoking content that invites genuine professional responses. "What's your experience with X?" (acceptable) vs "Type 1 if you agree" (penalized).

---

5. HOOK TEMPLATES PER PLATFORM

The 3-Second Rule: 84.3% of viral TikTok videos use psychological hook triggers within the first 3 seconds. Videos with 70-85% retention at 3 seconds receive 2.2x more total views.

INSTAGRAM HOOKS (<=125 chars):

| Type           | Template                                             | Example                                           |
|----------------|------------------------------------------------------|---------------------------------------------------|
| Curiosity gap  | "I tested [N] [things]. Only [N] were worth it."    | "I tested 50 AI tools. Only 3 were worth it."     |
| Bold claim     | "[N]% of [people] don't know this about [topic]."   | "98% of creators don't know this about AI."       |
| Question       | "Why are top [people] switching to [thing]?"         | "Why are top creators switching to AI carousels?"  |
| Data shock     | "[Shocking number] -- and most people ignore it."    | "120 terabytes per second -- and most people ignore it." |
| Contrarian     | "Stop [common advice]. Here's why."                  | "Stop posting Reels. Here's why."                 |

TIKTOK HOOKS (<=100 chars):

| Type           | Template                                             | Example                                           |
|----------------|------------------------------------------------------|---------------------------------------------------|
| POV            | "POV: you just discovered [thing]"                   | "POV: you just discovered AI carousel generators"  |
| Wait for it    | "This changes everything about [topic]..."           | "This changes everything about content creation..." |
| Ranking        | "[N] [things] ranked worst to best"                  | "5 AI tools ranked worst to best"                 |
| Challenge      | "Try this and thank me later"                        | "Try this and thank me later"                     |
| Relatable      | "When you realize [relatable thing]..."              | "When you realize AI can do your carousels..."     |
| Self-call-out  | "Not me [doing something relatable]..."              | "Not me spending 3 hours on a carousel..."        |
| Hyper-specific | "When [oddly specific scenario]..."                  | "When you open Canva for a 'quick edit' at 2am..." |
| Identity       | "Tell me you're [identity] without telling me"       | "Tell me you're a content creator without telling me" |
| Pipeline       | "The [thing] to [other thing] pipeline is real"      | "The 'just one more edit' to 3am pipeline is real" |

LINKEDIN HOOKS (<=110 chars):

| Type       | Template                                             | Example                                           |
|------------|------------------------------------------------------|---------------------------------------------------|
| Insight    | "After [N] years in [field], here's what I learned:" | "After 5 years in AI, here's what I learned:"     |
| Framework  | "The [Name] Framework for [outcome]:"                | "The 70/30 Framework for holiday content:"        |
| Data       | "[Company] just [did thing]. Here's what it means."  | "Google just launched Gemini 3. Here's what it means." |
| Contrarian | "Unpopular opinion: [take]"                          | "Unpopular opinion: Carousels outperform Reels."  |
| Story      | "I [did thing]. The results surprised me."           | "I replaced all my designs with AI. The results surprised me." |
| Wish list  | "[N] things I wish I knew about [topic]"             | "5 things I wish I knew about AI content creation" |

---

6. CTA BEST PRACTICES

CTA PSYCHOLOGY

Engagement Ladder (lowest -> highest commitment):
Like -> Save -> Comment -> Share/DM Send -> Follow

Key principles:
- One primary CTA per post -- single CTA = +371% clicks vs multiple CTAs. Multiple CTAs create decision fatigue.
- Micro-commitments -- small asks (poll tap, like) make users more likely to take bigger actions (comment, follow) due to consistency bias.
- Soft vs Hard CTA -- soft ("What's your experience?") for cold audiences; hard ("Comment GUIDE for the PDF") for warm audiences.
- Posts with clear CTAs = +25% CTR. Posts without CTA = massive missed opportunity.
- Carousel dual-CTA: soft CTA mid-carousel + hard CTA on last slide.

ALGORITHM WEIGHT SIGNALS PER PLATFORM:

| Signal           | Instagram                        | TikTok                                | LinkedIn                   |
|------------------|----------------------------------|---------------------------------------|----------------------------|
| DM shares/sends  | 3-5x heavier than likes          | High weight                           | N/A                        |
| Saves            | 3x heavier than likes            | Strongest signal                      | "Depth Score"              |
| Comments         | High value                       | High value (especially first hour)    | #1 distribution signal     |
| Likes            | Lowest weight                    | Moderate                              | Low (bait = -60% penalty)  |
| Watch/dwell time | #1 ranking factor (Mosseri Jan 2025) | Primary (70%+ completion for viral) | 2-3x more for carousels   |

CTA BY GOAL:

| Goal         | Best CTA Format                                    | Data                                              |
|--------------|----------------------------------------------------|----------------------------------------------------|
| Comments     | "Comment [KEYWORD] for free [resource]"            | +70% comments (IG), triggers DM automation         |
| Comments     | Fill-in-the-blank: "My favorite ___ is ___"        | Lowest barrier to entry                            |
| Comments     | "Agree or disagree: [bold claim]?"                 | Debate-driven, high volume                         |
| Comments     | "Which one would you pick?"                        | Simple choice = low friction                       |
| Saves        | "Save this for the next time you ___"              | +30% reach lift, 3x algorithm weight               |
| Shares       | "Send this to the person who handles ___"          | 3-5x algorithm weight on IG                        |
| Follows      | "Follow for [specific value] every [frequency]"    | Series content = +40-60% engagement                |
| Follows (TT) | Mid-roll CTA at 50% retention point                | 3x more effective than end-of-video                |
| Likes        | "Double tap if this resonates"                     | +11% engagement (IG only). Don't waste primary CTA on this |

COMMENT-TO-DM KEYWORD CTA FUNNEL:
"Comment [KEYWORD] and I'll DM you the [resource]" -- user comments keyword, automated DM (via ManyChat) delivers resource + captures email.
- IG: ManyChat integration mature, auto-DM works
- TikTok: viewer must message you first (auto-DM not fully supported yet)
- Can double lead volume (1,000+ leads/month reported)

PLATFORM-SPECIFIC CTA RULES:

| Platform  | Do                                                | Don't                                          |
|-----------|---------------------------------------------------|------------------------------------------------|
| Instagram | Save + Share CTAs (highest algorithm weight)      | Generic "like this post"                       |
| TikTok    | Question CTAs + "Save for later"                  | "PLEASE follow and share!" (desperate tone)    |
| LinkedIn  | Open questions inviting expertise                  | "Comment YES if you agree" (-60% reach penalty) |

CTA PHRASES THAT CONVERT:

| Action          | English                                  | Bahasa Indonesia                         |
|-----------------|------------------------------------------|------------------------------------------|
| Follow          | "Follow for daily [topic] tips"          | "Follow buat konten [topic] tiap hari"   |
| Save            | "Save this for when you need it"         | "Save post ini, penting!"               |
| Share           | "Send this to someone who needs it"      | "Share ke temen yang perlu tau"          |
| Comment         | "Which tip was most useful?"             | "Comment pendapat kamu"                  |
| Comment keyword | "Comment GUIDE for the free checklist"   | "Comment TEMPLATE buat dapetin gratis"   |
| Link            | "Full guide -> link in bio"              | "Link di bio ya"                         |

EMOJI USAGE IN CTAs:

| Platform  | Recommended         | Notes                                         |
|-----------|---------------------|-----------------------------------------------|
| Instagram | 3-5 relevant emojis per caption | +48% engagement. Use functional emojis (pointing, checkmarks) |
| TikTok    | 1-3 max             | Minimal emoji culture. Text-based wit preferred |
| LinkedIn  | Sparingly, never in first line | Professional context. Functional only    |

---

7. TIKTOK KEYWORD SEO (4 LAYERS)

TikTok indexes 4 text layers simultaneously for content classification and search:

| Layer            | What It Is                        | SEO Weight                                     |
|------------------|-----------------------------------|-------------------------------------------------|
| Title            | Separate 19-char field above caption | Highest -- always visible, primary keyword signal |
| Caption text     | Description below video           | High -- first 3 words = secondary SEO weight   |
| On-screen text   | Text overlay on video/image       | OCR-scanned within first 2-3 seconds           |
| Spoken audio     | Voice in video                    | Transcribed and indexed automatically          |

Strategy: Use different but related keywords across all 4 layers to maximize keyword coverage. Title carries the primary keyword, caption carries supporting keywords.

Example:
- Title: "AI Tools 2026" (19 chars max)
- Caption: "These 5 tools just changed the game for content creators"
- On-screen text: "5am productivity hack"
- Spoken: "morning routine"

- Title = primary SEO keyword (max 19 chars, always visible)
- Place supporting keyword within first 3 words of caption
- Use 2-3 keywords naturally across caption (avoid keyword stuffing)
- 40% of Gen Z uses TikTok over Google for search -- title + caption SEO matters

---

8. BAHASA INDONESIA CAPTION CONVENTIONS

When writing captions in Bahasa Indonesia (on user request or for Indonesian-audience carousels).

LANGUAGE RULES:
- Use "kamu" not "Anda" (unless targeting corporate LinkedIn)
- Mix Bahasa + English naturally: "Ini literally mind-blowing banget"
- Slang OK for IG/TikTok: "gue/gw", "lo", "nggak", "banget", "slay"
- LinkedIn: professional Bahasa, minimal slang
- Short punchy sentences for all platforms

BAHASA CAPTION TEMPLATE:

[Bahasa hook -- provocative question or bold claim in mixed Bahasa-English]

[Bahasa body -- keep it casual for IG/TikTok, professional for LinkedIn, conversational for Threads]
[Use Indonesian references and context]

[Bahasa CTA -- see CTA phrases table above]

[Mix English and Bahasa hashtags (omit for Threads)]

BAHASA HOOK EXAMPLES:

| English                                | Bahasa Adaptation                              |
|----------------------------------------|------------------------------------------------|
| "What Actually Happens in 1 Second"    | "YANG TERJADI DALAM 1 DETIK DI BUMI"         |
| "7 AI Tools You Need Right Now"        | "7 TOOLS AI YANG KAMU HARUS COBA SEKARANG"   |
| "This will change everything"          | "INI BAKAL UBAH SEGALANYA"                    |
| "Stop doing this mistake"              | "STOP LAKUIN KESALAHAN INI"                   |
| "You won't believe this"              | "KAMU NGGAK BAKAL PERCAYA INI"               |

---

9. CROSS-PLATFORM CAPTION ADAPTATION

When adapting the same carousel across platforms:

| From -> To        | Key Adjustments                                              |
|-------------------|--------------------------------------------------------------|
| IG -> TikTok      | More casual, shorter, add trend references, same hashtag count |
| IG -> LinkedIn    | More professional, add data/framework, different hashtags, add link |
| TikTok -> IG      | Slightly more polished, keep energy, adjust hashtags         |
| TikTok -> LinkedIn| Complete tone shift, add insight/framework, professional language |
| LinkedIn -> IG    | Simplify, add personality, visual language, emojis OK        |
| LinkedIn -> TikTok| Casual rewrite, Gen Z tone, trending references              |

ADAPTATION CHECKLIST:
- Hook fits within platform truncation point
- Tone matches platform culture
- Hashtag count matches platform rules (IG 5/TikTok 5/LinkedIn 3-5/Threads 0)
- CTA uses platform-native actions (save/share vs repost)
- TikTok title is <=19 chars with primary SEO keyword
- Threads version stays under 500 chars, no hashtags
- Character count within platform limit
- Caption language matches user preference (English default)
- In-image text: per global config Language section (bilingual default). Single language on user request
- No cross-platform watermarks (IG deprioritizes TikTok watermarks and vice versa)
- Emoji density matches platform culture (3-5 IG, 1-3 TikTok, minimal LinkedIn)
`;
