import React from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, FileText } from "lucide-react";

export const Terms: React.FC = () => {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border-default bg-card/50 backdrop-blur-sm sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center gap-4">
          <Link
            to="/"
            className="flex items-center gap-2 text-text-secondary hover:text-text-primary transition-colors"
          >
            <ArrowLeft className="w-5 h-5" />
            <span>Back</span>
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-6 py-12">
        <div className="flex items-center gap-3 mb-8">
          <div className="w-12 h-12 bg-primary/10 rounded-xl flex items-center justify-center">
            <FileText className="w-6 h-6 text-primary" />
          </div>
          <div>
            <h1 className="text-3xl font-bold text-text-primary">Terms of Service</h1>
            <p className="text-text-secondary">Last updated: January 10, 2026</p>
          </div>
        </div>

        <div className="prose prose-invert max-w-none space-y-8 text-text-secondary">
          <section>
            <h2 className="text-xl font-semibold text-text-primary mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Sparkfluence ("Service"), you agree to be bound by these Terms
              of Service ("Terms"). If you do not agree to these Terms, please do not use our Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-text-primary mb-4">2. Description of Service</h2>
            <p>
              Sparkfluence is an AI-powered platform that helps users create viral short-form video
              content for social media platforms including TikTok, Instagram Reels, and YouTube Shorts.
              Our services include script generation, image creation, video generation, and social
              media integration.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-text-primary mb-4">3. User Accounts</h2>
            <p className="mb-4">To use our Service, you must:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Be at least 18 years old or have parental consent</li>
              <li>Provide accurate and complete registration information</li>
              <li>Maintain the security of your account credentials</li>
              <li>Notify us immediately of any unauthorized use of your account</li>
              <li>Be responsible for all activities that occur under your account</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-text-primary mb-4">4. Acceptable Use</h2>
            <p className="mb-4">You agree not to use the Service to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Create content that is illegal, harmful, threatening, or discriminatory</li>
              <li>Infringe on any third party's intellectual property rights</li>
              <li>Spread misinformation or deceptive content</li>
              <li>Harass, abuse, or harm another person</li>
              <li>Attempt to gain unauthorized access to our systems</li>
              <li>Use the Service for any illegal or unauthorized purpose</li>
              <li>Violate the terms of service of connected platforms (YouTube, Instagram, TikTok)</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-text-primary mb-4">5. Content Ownership</h2>
            <p className="mb-4">
              <strong>Your Content:</strong> You retain ownership of all content you create using
              our Service. By using our Service, you grant us a limited license to process and
              store your content as necessary to provide the Service.
            </p>
            <p>
              <strong>AI-Generated Content:</strong> Content generated by our AI tools is provided
              for your use. You are responsible for ensuring your use of AI-generated content
              complies with applicable laws and platform guidelines.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-text-primary mb-4">6. Social Media Integration</h2>
            <p className="mb-4">
              When you connect your social media accounts (YouTube, Instagram, TikTok) to Sparkfluence:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>You authorize us to post content on your behalf</li>
              <li>You remain responsible for all content posted to your accounts</li>
              <li>You must comply with each platform's terms of service</li>
              <li>You can disconnect your accounts at any time</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-text-primary mb-4">7. Payment Terms</h2>
            <p className="mb-4">For paid features:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Payments are processed securely through Stripe</li>
              <li>Subscription fees are billed in advance on a recurring basis</li>
              <li>Sparks credits are non-refundable once used</li>
              <li>You can cancel your subscription at any time</li>
              <li>Refunds are handled on a case-by-case basis</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-text-primary mb-4">8. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Sparkfluence shall not be liable for any
              indirect, incidental, special, consequential, or punitive damages, including loss of
              profits, data, or goodwill, arising out of or in connection with your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-text-primary mb-4">9. Disclaimer of Warranties</h2>
            <p>
              The Service is provided "as is" and "as available" without warranties of any kind,
              either express or implied. We do not guarantee that the Service will be uninterrupted,
              secure, or error-free.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-text-primary mb-4">10. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your access to the Service at any time,
              with or without cause, and with or without notice. Upon termination, your right to
              use the Service will immediately cease.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-text-primary mb-4">11. Changes to Terms</h2>
            <p>
              We may modify these Terms at any time. We will notify you of any material changes by
              posting the new Terms on this page. Your continued use of the Service after such
              changes constitutes your acceptance of the new Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-text-primary mb-4">12. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the
              Republic of Indonesia, without regard to its conflict of law provisions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-text-primary mb-4">13. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us at:{" "}
              <a href="mailto:legal@sparkfluence.com" className="text-primary hover:underline">
                legal@sparkfluence.com
              </a>
            </p>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-border-default mt-12 py-8">
        <div className="max-w-4xl mx-auto px-6 text-center text-text-secondary text-sm">
          <p>© 2026 Sparkfluence. All rights reserved.</p>
          <div className="flex justify-center gap-4 mt-2">
            <Link to="/privacy" className="hover:text-primary">Privacy Policy</Link>
            <span>•</span>
            <Link to="/terms" className="hover:text-primary">Terms of Service</Link>
          </div>
        </div>
      </footer>
    </div>
  );
};
